force-app/main/default/objects/Project_Phase__c/Project_Phase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Phase__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tower Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sub_Unit__c/Sub_Unit__c.object-meta.xml
<CustomObject>
    <label>Sub Unit</label>
    <nameField>
        <label>Sub Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Sub Units</relationshipLabel>
    <relationshipName>Sub_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>Project_Phase__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SiteVisitLookupController.cls
public with sharing class SiteVisitLookupController {
    
    @AuraEnabled(cacheable=true)
    public static List<Project_Phase__c> getProjectPhases() {
        return [
            SELECT Id, Name
            FROM Project_Phase__c
            ORDER BY Name
        ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Tower__c> getTowers() {
        return [
            SELECT Id, Name
            FROM Tower__c
            ORDER BY Name
        ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Sub_Unit__c> getSubUnits() {
        return [
            SELECT Id, Name
            FROM Sub_Unit__c
            ORDER BY Name
        ];
    }
    
}