force-app/main/default/objects/Project_Phase__c/Project_Phase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Phase__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tower Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_Unit__c/Property_Unit__c.object-meta.xml
<CustomObject>
    <label>Property Unit</label>
    <nameField>
        <label>Property Unit  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Property Units</relationshipLabel>
    <relationshipName>Property_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sub_Unit__c/Sub_Unit__c.object-meta.xml
<CustomObject>
    <label>Sub Unit</label>
    <nameField>
        <label>Sub Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Unit__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Unit</label>
    <referenceTo>Property_Unit__c</referenceTo>
    <relationshipLabel>Sub Units</relationshipLabel>
    <relationshipName>Sub_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sub_Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Sub Units</relationshipLabel>
    <relationshipName>Sub_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>Project_Phase__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TowerWithUnitsController.cls
public with sharing class TowerWithUnitsController {

    @AuraEnabled(cacheable=true)
    public static List<Tower__c> getTowersWithUnits(Id phaseId) {
        if (phaseId == null) {
            return new List<Tower__c>();
        }

        return [
            SELECT Id, Name,
                (SELECT Id, Name,
                        (SELECT Id, Name FROM Sub_Units__r)
                 FROM Property_Units__r)
            FROM Tower__c
            WHERE Project_Phase__c = :phaseId
            ORDER BY Name
        ];
    }

}